/*
  Add needed indexes on various tables.

  Last Revision Details:
    $Revision: 1 $
    $Date: 21/02/03 11:41 $
    $Author: Ericsalmon $
  
*/

-- SURVEY_EVENT_RECORDER
CREATE INDEX [IX_SURVEY_EVENT_KEY] ON [dbo].[SURVEY_EVENT_RECORDER]([SURVEY_EVENT_KEY]) 
WITH DROP_EXISTING
ON [PRIMARY]
GO

-- SAMPLE table
CREATE INDEX [IX_SURVEY_EVENT_KEY] ON [dbo].[SAMPLE]([SURVEY_EVENT_KEY]) 
WITH DROP_EXISTING
ON [PRIMARY]
GO

-- TAXON_DETERMINATION table
CREATE CLUSTERED INDEX [IX_TAXON_OCCURRENCE_KEY] ON [dbo].[TAXON_DETERMINATION]([TAXON_OCCURRENCE_KEY]) 
WITH DROP_EXISTING
ON [PRIMARY]
GO

CREATE INDEX [IX_PREFERRED] ON [dbo].[TAXON_DETERMINATION]([PREFERRED]) 
WITH DROP_EXISTING
ON [PRIMARY]
GO

-- TAXON_OCCURRENCE table
CREATE INDEX [IX_SAMPLE_KEY] ON [dbo].[TAXON_OCCURRENCE]([SAMPLE_KEY]) 
WITH DROP_EXISTING
ON [PRIMARY]
GO

-- BIOTOPE_DETERMINATION table
CREATE CLUSTERED INDEX [IX_BIOTOPE_OCCURRENCE_KEY] ON [dbo].[BIOTOPE_DETERMINATION]([BIOTOPE_OCCURRENCE_KEY]) 
WITH DROP_EXISTING
ON [PRIMARY]
GO

CREATE INDEX [IX_PREFERRED] ON [dbo].[BIOTOPE_DETERMINATION]([PREFERRED]) 
WITH DROP_EXISTING
ON [PRIMARY]
GO
