/*
  Drop superfluous indexes.

  Last Revision Details:
    $Revision: 1 $
    $Date: 21/02/03 11:41 $
    $Author: Ericsalmon $
  
*/

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[BIOTOPE_LIST_ITEM_KEY]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[BIOTOPE_LIST_ITEMBIOTOPE_DETERMINATION]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[BIOTOPE_OCCURRENCE_KEY]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[BIOTOPE_OCCURRENCEBIOTOPE_DETERMINATION]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[DETERMINATION_TYPE_KEY]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[DETERMINATION_TYPEBIOTOPE_DETERMINATION]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[DETERMINER]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[DETERMINER_ROLE_KEY]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[DETERMINER_ROLEBIOTOPE_DETERMINATION]
GO

DROP INDEX [dbo].[BIOTOPE_DETERMINATION].[NAMEBIOTOPE_DETERMINATION]
GO

DROP INDEX [dbo].[ADMIN_AREA].[ADMIN_AREA_KEY]
GO

DROP INDEX [dbo].[ADMIN_AREA_SOURCES].[ADMIN_AREAADMIN_AREA_SOURCES]
GO

DROP INDEX [dbo].[ADMIN_AREA_SOURCES].[SOURCEADMIN_AREA_SOURCES]
GO

DROP INDEX [dbo].[BIOTOPE_CLASSIFICATION].[BT_CL_TYPE_KEY]
GO

DROP INDEX [dbo].[BIOTOPE_CLASSIFICATION_VERSION].[BIOTOPE_CLASSIFICATION_KEY]
GO

DROP INDEX [dbo].[BIOTOPE_OCCURRENCE_DATA].[MEASUREMENT_UNIT_KEY]
GO

DROP INDEX [dbo].[INDIVIDUAL].[NAME_KEY]
GO

DROP INDEX [dbo].[LOCATION_DATA].[MEASUREMENT_UNIT_KEY]
GO

DROP INDEX [dbo].[REFERENCE_NUMBER].[REFERENCEREFERENCE_NUMBER]
GO

DROP INDEX [dbo].[SAMPLE_DATA].[MEASUREMENT_UNIT_KEY]
GO

DROP INDEX [dbo].[SOURCE].[SOURCE_KEY]
GO