If EXISTS (SELECT * FROM SysObjects WHERE Id = OBJECT_ID(N'[dbo].[spControlCustodianTriggers]') AND OBJECTPROPERTY(Id, N'IsProcedure') = 1)
    BEGIN
        PRINT 'Dropping procedure spControlCustodianTriggers'
        DROP PROCEDURE [dbo].[spControlCustodianTriggers]
    END
GO

    PRINT 'Creating procedure spControlCustodianTriggers'
GO

/*
    $History: spControlCustodianTriggers.sql $
 * 
 * *****************  Version 2  *****************
 * User: Bencollier   Date: 7/02/03    Time: 10:14
 * Updated in $/JNCC/Development/Build/SQL Scripts/Stored Procs
 * Updated permissions at end of script
 * 
 * *****************  Version 1  *****************
 * User: Bencollier   Date: 14/01/03   Time: 17:29
 * Created in $/JNCC/Development/Build/SQL Scripts/Stored Procs
 * Initial Build
 */

CREATE PROCEDURE dbo.spControlCustodianTriggers
--
--	DESCRIPTION
--	This procedure enables or disables the triggers required to maintain the custodian field for each table.
--
--	PARAMETERS
--	NAME			DESCRIPTION
--
--
--	AUTHOR:	Ben Collier, Dorset Software.
--	CREATED: 14/01/2003
--
--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
@Enable bit
--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AS
SET NOCOUNT ON

IF @Enable = 1
BEGIN
	ALTER TABLE [ADDRESS] ENABLE TRIGGER ALL
	ALTER TABLE [ADMIN_AREA] ENABLE TRIGGER ALL
	ALTER TABLE [ADMIN_BOUNDARY] ENABLE TRIGGER ALL
	ALTER TABLE [ADMIN_RELATION] ENABLE TRIGGER ALL
	ALTER TABLE [ADMIN_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_CLASSIFICATION] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_CLASSIFICATION_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_CLASSIFICATION_VERSION] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_DESIGNATION] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_DESIGNATION_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_DETERMINATION] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_FACT] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_LIST_ITEM] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_OCCURRENCE] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_OCCURRENCE_DATA] ENABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_RELATION] ENABLE TRIGGER ALL
	ALTER TABLE [COMMUNICATION] ENABLE TRIGGER ALL
	ALTER TABLE [CONTACT_NUMBER] ENABLE TRIGGER ALL
	ALTER TABLE [DAMAGE_OCCURRENCE] ENABLE TRIGGER ALL
	ALTER TABLE [DETERMINATION_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [DETERMINER_ROLE] ENABLE TRIGGER ALL
	ALTER TABLE [GRID_SQUARE] ENABLE TRIGGER ALL
	ALTER TABLE [JOURNAL] ENABLE TRIGGER ALL
	ALTER TABLE [LAND_PARCEL] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_ADMIN_AREAS] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_BOUNDARY] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_DATA] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_DESIGNATION] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_FEATURE] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_FEATURE_GRADING] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_FEATURE_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_NAME] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_RELATION] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_USE] ENABLE TRIGGER ALL
	ALTER TABLE [MANAGEMENT_AIM] ENABLE TRIGGER ALL
	ALTER TABLE [MEASUREMENT_QUALIFIER] ENABLE TRIGGER ALL
	ALTER TABLE [MEASUREMENT_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [MEASUREMENT_UNIT] ENABLE TRIGGER ALL
	ALTER TABLE [NAME] ENABLE TRIGGER ALL
	ALTER TABLE [NAME_RELATION] ENABLE TRIGGER ALL
	ALTER TABLE [ORGANISATION_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [POTENTIAL_THREAT] ENABLE TRIGGER ALL
	ALTER TABLE [LOCATION_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [RECORD_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [RECORDER_ROLE] ENABLE TRIGGER ALL
	ALTER TABLE [REFERENCE_AUTHOR] ENABLE TRIGGER ALL
	ALTER TABLE [REFERENCE_EDITOR] ENABLE TRIGGER ALL
	ALTER TABLE [REFERENCE_NUMBER] ENABLE TRIGGER ALL
	ALTER TABLE [RELATIONSHIP_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [SAMPLE] ENABLE TRIGGER ALL
	ALTER TABLE [SAMPLE_DATA] ENABLE TRIGGER ALL
	ALTER TABLE [SAMPLE_RELATION] ENABLE TRIGGER ALL
	ALTER TABLE [SAMPLE_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [SITE_STATUS] ENABLE TRIGGER ALL
	ALTER TABLE [SOURCE] ENABLE TRIGGER ALL
	ALTER TABLE [SPECIMEN] ENABLE TRIGGER ALL
	ALTER TABLE [SPECIMEN_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [SUBSTRATE] ENABLE TRIGGER ALL
	ALTER TABLE [SURVEY] ENABLE TRIGGER ALL
	ALTER TABLE [SURVEY_EVENT] ENABLE TRIGGER ALL
	ALTER TABLE [SURVEY_EVENT_RECORDER] ENABLE TRIGGER ALL
	ALTER TABLE [SURVEY_MEDIA] ENABLE TRIGGER ALL
	ALTER TABLE [SURVEY_STATUS] ENABLE TRIGGER ALL
	ALTER TABLE [SURVEY_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_BIOTOPE_ASSOCIATION] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_DESIGNATION] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_DESIGNATION_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_DETERMINATION] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_FACT] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST_ITEM] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST_VERSION] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_NAME_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_OCCURRENCE] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_OCCURRENCE_DATA] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_OCCURRENCE_RELATION] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_RANK] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_TAXON_ASSOCIATION] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_VERSION] ENABLE TRIGGER ALL
	ALTER TABLE [TAXON_VERSION_RELATION] ENABLE TRIGGER ALL
	ALTER TABLE [TENURE] ENABLE TRIGGER ALL
	ALTER TABLE [TENURE_TYPE] ENABLE TRIGGER ALL
	ALTER TABLE [THREAT_TYPE] ENABLE TRIGGER ALL
END
ELSE
BEGIN
	ALTER TABLE [ADDRESS] DISABLE TRIGGER ALL
	ALTER TABLE [ADMIN_AREA] DISABLE TRIGGER ALL
	ALTER TABLE [ADMIN_BOUNDARY] DISABLE TRIGGER ALL
	ALTER TABLE [ADMIN_RELATION] DISABLE TRIGGER ALL
	ALTER TABLE [ADMIN_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_CLASSIFICATION] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_CLASSIFICATION_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_CLASSIFICATION_VERSION] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_DESIGNATION] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_DESIGNATION_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_DETERMINATION] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_FACT] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_LIST_ITEM] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_OCCURRENCE] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_OCCURRENCE_DATA] DISABLE TRIGGER ALL
	ALTER TABLE [BIOTOPE_RELATION] DISABLE TRIGGER ALL
	ALTER TABLE [COMMUNICATION] DISABLE TRIGGER ALL
	ALTER TABLE [CONTACT_NUMBER] DISABLE TRIGGER ALL
	ALTER TABLE [DAMAGE_OCCURRENCE] DISABLE TRIGGER ALL
	ALTER TABLE [DETERMINATION_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [DETERMINER_ROLE] DISABLE TRIGGER ALL
	ALTER TABLE [GRID_SQUARE] DISABLE TRIGGER ALL
	ALTER TABLE [JOURNAL] DISABLE TRIGGER ALL
	ALTER TABLE [LAND_PARCEL] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_ADMIN_AREAS] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_BOUNDARY] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_DATA] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_DESIGNATION] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_FEATURE] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_FEATURE_GRADING] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_FEATURE_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_NAME] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_RELATION] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_USE] DISABLE TRIGGER ALL
	ALTER TABLE [MANAGEMENT_AIM] DISABLE TRIGGER ALL
	ALTER TABLE [MEASUREMENT_QUALIFIER] DISABLE TRIGGER ALL
	ALTER TABLE [MEASUREMENT_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [MEASUREMENT_UNIT] DISABLE TRIGGER ALL
	ALTER TABLE [NAME] DISABLE TRIGGER ALL
	ALTER TABLE [NAME_RELATION] DISABLE TRIGGER ALL
	ALTER TABLE [ORGANISATION_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [POTENTIAL_THREAT] DISABLE TRIGGER ALL
	ALTER TABLE [LOCATION_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [RECORD_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [RECORDER_ROLE] DISABLE TRIGGER ALL
	ALTER TABLE [REFERENCE_AUTHOR] DISABLE TRIGGER ALL
	ALTER TABLE [REFERENCE_EDITOR] DISABLE TRIGGER ALL
	ALTER TABLE [REFERENCE_NUMBER] DISABLE TRIGGER ALL
	ALTER TABLE [RELATIONSHIP_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [SAMPLE] DISABLE TRIGGER ALL
	ALTER TABLE [SAMPLE_DATA] DISABLE TRIGGER ALL
	ALTER TABLE [SAMPLE_RELATION] DISABLE TRIGGER ALL
	ALTER TABLE [SAMPLE_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [SITE_STATUS] DISABLE TRIGGER ALL
	ALTER TABLE [SOURCE] DISABLE TRIGGER ALL
	ALTER TABLE [SPECIMEN] DISABLE TRIGGER ALL
	ALTER TABLE [SPECIMEN_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [SUBSTRATE] DISABLE TRIGGER ALL
	ALTER TABLE [SURVEY] DISABLE TRIGGER ALL
	ALTER TABLE [SURVEY_EVENT] DISABLE TRIGGER ALL
	ALTER TABLE [SURVEY_EVENT_RECORDER] DISABLE TRIGGER ALL
	ALTER TABLE [SURVEY_MEDIA] DISABLE TRIGGER ALL
	ALTER TABLE [SURVEY_STATUS] DISABLE TRIGGER ALL
	ALTER TABLE [SURVEY_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_BIOTOPE_ASSOCIATION] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_DESIGNATION] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_DESIGNATION_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_DETERMINATION] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_FACT] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST_ITEM] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_LIST_VERSION] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_NAME_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_OCCURRENCE] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_OCCURRENCE_DATA] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_OCCURRENCE_RELATION] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_RANK] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_TAXON_ASSOCIATION] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_VERSION] DISABLE TRIGGER ALL
	ALTER TABLE [TAXON_VERSION_RELATION] DISABLE TRIGGER ALL
	ALTER TABLE [TENURE] DISABLE TRIGGER ALL
	ALTER TABLE [TENURE_TYPE] DISABLE TRIGGER ALL
	ALTER TABLE [THREAT_TYPE] DISABLE TRIGGER ALL
END
--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GO

    IF EXISTS (SELECT * FROM SysObjects WHERE Id = OBJECT_ID('dbo.spControlCustodianTriggers') AND SysStat & 0xf = 4)
    BEGIN
        PRINT 'Setting up security on procedure spControlCustodianTriggers'
        IF EXISTS (SELECT * FROM SYSUSERS WHERE NAME = 'Dev- JNCC SQL')
        	GRANT EXECUTE ON dbo.spControlCustodianTriggers TO [Dev- JNCC SQL]

		IF EXISTS (SELECT * FROM SYSUSERS WHERE NAME = 'R2k_Administrator')
       		GRANT EXECUTE ON dbo.spControlCustodianTriggers TO [R2k_Administrator]
    END
GO