SELECT   SAMPLE.SAMPLE_KEY, SAMPLE.SPATIAL_REF, ADMIN_AREA.SHORT_CODE AS VC
FROM     ADMIN_AREA INNER JOIN
           LOCATION_ADMIN_AREAS ON ADMIN_AREA.ADMIN_AREA_KEY = LOCATION_ADMIN_AREAS.ADMIN_AREA_KEY INNER JOIN
           SAMPLE ON LOCATION_ADMIN_AREAS.LOCATION_KEY = SAMPLE.LOCATION_KEY
WHERE    (ADMIN_AREA.ADMIN_TYPE_KEY = 'NBNSYS0000000032') AND (SAMPLE.SPATIAL_REF_SYSTEM = 'OSGB')
ORDER BY SAMPLE.SAMPLE_KEY