if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FK_REPORT_FIELD_REPORT_ATTRIBUTE]') and OBJECTPROPERTY(id, N'IsForeignKey') = 1)
ALTER TABLE [dbo].[REPORT_FIELD] DROP CONSTRAINT FK_REPORT_FIELD_REPORT_ATTRIBUTE
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[REPORT_ATTRIBUTE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[REPORT_ATTRIBUTE]
GO

CREATE TABLE [dbo].[REPORT_ATTRIBUTE] (
	[REPORT_ATTRIBUTE_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[ITEM_GROUP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SOURCE_TABLE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ITEM_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[ATTRIBUTE_SQL] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[REPORT_JOIN_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[REPORT_WHERE_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ENTERED_BY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ENTRY_DATE] [smalldatetime] NULL ,
	[CHANGED_BY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CHANGED_DATE] [smalldatetime] NULL ,
	[SYSTEM_SUPPLIED_DATA] [bit] NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[REPORT_ATTRIBUTE] WITH NOCHECK ADD 
	CONSTRAINT [PK_REPORT_ATTRIBUTE] PRIMARY KEY  CLUSTERED 
	(
		[REPORT_ATTRIBUTE_KEY]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[REPORT_ATTRIBUTE] ADD 
	CONSTRAINT [DF_REPORT_ATTRIBUTE_ENTRY_DATE] DEFAULT (getdate()) FOR [ENTRY_DATE],
	CONSTRAINT [DF_REPORT_ATTRIBUTE_SYSTEM_SUPPLIED_DATA] DEFAULT (0) FOR [SYSTEM_SUPPLIED_DATA]
GO

 CREATE  INDEX [REPORT_JOIN_KEY] ON [dbo].[REPORT_ATTRIBUTE]([REPORT_JOIN_KEY]) ON [PRIMARY]
GO

 CREATE  INDEX [REPORT_WHERE_KEY] ON [dbo].[REPORT_ATTRIBUTE]([REPORT_WHERE_KEY]) ON [PRIMARY]
GO

GRANT  SELECT  ON [dbo].[REPORT_ATTRIBUTE]  TO [R2k_ReadOnly]
GO

GRANT  SELECT  ON [dbo].[REPORT_ATTRIBUTE]  TO [R2k_RecordCardsOnly]
GO

GRANT  SELECT  ON [dbo].[REPORT_ATTRIBUTE]  TO [R2k_AddOnly]
GO

GRANT  SELECT  ON [dbo].[REPORT_ATTRIBUTE]  TO [R2k_FullEdit]
GO

GRANT  SELECT  ON [dbo].[REPORT_ATTRIBUTE]  TO [R2k_Administrator]
GO

ALTER TABLE [dbo].[REPORT_ATTRIBUTE] ADD 
	CONSTRAINT [FK_REPORT_ATTRIBUTE_REPORT_JOIN] FOREIGN KEY 
	(
		[REPORT_JOIN_KEY]
	) REFERENCES [dbo].[REPORT_JOIN] (
		[REPORT_JOIN_KEY]
	),
	CONSTRAINT [FK_REPORT_ATTRIBUTE_REPORT_WHERE] FOREIGN KEY 
	(
		[REPORT_WHERE_KEY]
	) REFERENCES [dbo].[REPORT_WHERE] (
		[REPORT_WHERE_KEY]
	)
GO

