if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[REPORT_FIELD]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[REPORT_FIELD]
GO

CREATE TABLE [dbo].[REPORT_FIELD] (
	[REPORT_FIELD_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[REPORT_ATTRIBUTE_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[FIELD_ITEM_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[FIELD_TYPE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[FIELD_SIZE] [int] NULL ,
	[ENTERED_BY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ENTRY_DATE] [smalldatetime] NULL ,
	[CHANGED_BY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CHANGED_DATE] [smalldatetime] NULL ,
	[SYSTEM_SUPPLIED_DATA] [bit] NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[REPORT_FIELD] WITH NOCHECK ADD 
	CONSTRAINT [PK_REPORT_FIELD_KEY] PRIMARY KEY  CLUSTERED 
	(
		[REPORT_FIELD_KEY]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[REPORT_FIELD] ADD 
	CONSTRAINT [DF_REPORT_FIELD_ENTRY_DATE] DEFAULT (getdate()) FOR [ENTRY_DATE],
	CONSTRAINT [DF_REPORT_FIELD_SYSTEM_SUPPLIED_DATA] DEFAULT (0) FOR [SYSTEM_SUPPLIED_DATA]
GO

 CREATE  INDEX [REPORT_ATTRIBUTE_KEY] ON [dbo].[REPORT_FIELD]([REPORT_ATTRIBUTE_KEY]) ON [PRIMARY]
GO

GRANT  SELECT  ON [dbo].[REPORT_FIELD]  TO [R2k_ReadOnly]
GO

GRANT  SELECT  ON [dbo].[REPORT_FIELD]  TO [R2k_RecordCardsOnly]
GO

GRANT  SELECT  ON [dbo].[REPORT_FIELD]  TO [R2k_AddOnly]
GO

GRANT  SELECT  ON [dbo].[REPORT_FIELD]  TO [R2k_FullEdit]
GO

GRANT  SELECT  ON [dbo].[REPORT_FIELD]  TO [R2k_Administrator]
GO

ALTER TABLE [dbo].[REPORT_FIELD] ADD 
	CONSTRAINT [FK_REPORT_FIELD_REPORT_ATTRIBUTE] FOREIGN KEY 
	(
		[REPORT_ATTRIBUTE_KEY]
	) REFERENCES [dbo].[REPORT_ATTRIBUTE] (
		[REPORT_ATTRIBUTE_KEY]
	)
GO

