ALTER TABLE INDEX_TAXON_GROUP
	DROP CONSTRAINT [PK_INDEX_TAXON_GROUP]
GO

ALTER TABLE INDEX_TAXON_GROUP
	ADD CONSTRAINT [PK_INDEX_TAXON_GROUP] PRIMARY KEY NONCLUSTERED 
(
	[TAXON_LIST_ITEM_KEY] ASC,
	[CONTAINED_LIST_ITEM_KEY] ASC
)
GO

IF EXISTS (SELECT name FROM sysindexes where name = 'IX_INDEX_TAXON_GROUP_TAXON_LIST_ITEM_KEY')
	DROP INDEX INDEX_TAXON_GROUP.IX_INDEX_TAXON_GROUP_TAXON_LIST_ITEM_KEY
GO

CREATE CLUSTERED INDEX [IX_INDEX_TAXON_GROUP_TAXON_LIST_ITEM_KEY] ON [dbo].[INDEX_TAXON_GROUP] 
(
	[TAXON_LIST_ITEM_KEY] ASC
)
GO

IF EXISTS (SELECT name FROM sysindexes where name = 'IX_INDEX_TAXON_GROUP_CONTAINED_LIST_ITEM_KEY')
	DROP INDEX INDEX_TAXON_GROUP.IX_INDEX_TAXON_GROUP_CONTAINED_LIST_ITEM_KEY
GO

CREATE NONCLUSTERED INDEX [IX_INDEX_TAXON_GROUP_CONTAINED_LIST_ITEM_KEY] ON [dbo].[INDEX_TAXON_GROUP] 
(
	[CONTAINED_LIST_ITEM_KEY] ASC
)
GO