/********* Adds Unparsed Determiners to Private Data *****************/

INSERT INTO TAXON_PRIVATE_TYPE (TAXON_PRIVATE_TYPE_KEY,SHORT_NAME,LONG_NAME,ENTERED_BY,
ENTRY_DATE,CUSTODIAN,SYSTEM_SUPPLIED_DATA,DESCRIPTION)
VALUES ('R6TEAM1800000002','Unparsed Determiner','Unparsed Determiner','TESTDATA00000001',
getdate(),'R6TEAM18',1,'Item value = Determiner (or None), detail is the unparsed name')

GO
DELETE FROM IW_COLUMN_TYPE_PATTERN WHERE IW_COLUMN_TYPE_KEY = 'LCA00023000000R8'

GO

INSERT INTO IW_COLUMN_TYPE (IW_COLUMN_TYPE_KEY,CLASS_NAME,ITEM_NAME,
[REQUIRED], Commonly_Used,SEQUENCE,PARSER_CLASS_NAME,MAXIMUM_LENGTH,
ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','TColumnType','Unparsed Determiners',0,0,11,
'TTextParser',100,'TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_COLUMN_TYPE_PATTERN (IW_COLUMN_TYPE_KEY,PATTERN,Exclude_Match,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES('LCA0002300000800','Unparsed Det',0,'TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE (IW_TABLE_RULE_KEY,SEQUENCE,TABLE_NAME,Filter_Expression,
ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800',21,'Taxon_Private_data','#master.LCA0002300000800_data <> ''''', 'TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_OUTPUT_FIELD (IW_OUTPUT_FIELD_KEY,NAME,DATA_TYPE,IW_COLUMN_TYPE_KEY,SOURCE_FIELD_NAME,
GENERATING_CLASS_NAME,GENERATOR_FIELD_INDEX,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','Detail','varchar(100)','LCA0002300000800',
'data',null,null,'TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_OUTPUT_FIELD (IW_OUTPUT_FIELD_KEY,NAME,DATA_TYPE,IW_COLUMN_TYPE_KEY,SOURCE_FIELD_NAME,
GENERATING_CLASS_NAME,GENERATOR_FIELD_INDEX,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000801','Taxon_Private_Data_Key','Char(16)',null,
null,'TKeyFieldGenerator',0,'TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_OUTPUT_FIELD (IW_OUTPUT_FIELD_KEY,NAME,DATA_TYPE,SOURCE_FIELD_NAME,
GENERATING_CLASS_NAME,GENERATOR_FIELD_INDEX,LITERAL_VALUE,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000802','Item_Name','varChar(30)',null,
null,null,'''Determiners''','TESTDATA00000001',getdate(),1)


GO


INSERT INTO IW_OUTPUT_FIELD (IW_OUTPUT_FIELD_KEY,NAME,DATA_TYPE,SOURCE_FIELD_NAME,
GENERATING_CLASS_NAME,GENERATOR_FIELD_INDEX,LITERAL_VALUE,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000803','Item_Date','smalldatetime',null,
null,null,'getdate()','TESTDATA00000001',getdate(),1)


GO

INSERT INTO IW_OUTPUT_FIELD (IW_OUTPUT_FIELD_KEY,NAME,DATA_TYPE,SOURCE_FIELD_NAME,
GENERATING_CLASS_NAME,GENERATOR_FIELD_INDEX,LITERAL_VALUE,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000804','Taxon_Private_Type_Key','Char(16)',null,
null,null,'''R6TEAM1800000002''','TESTDATA00000001',getdate(),1)


GO


INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','LCA0002300000800','TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','LCA0002300000801','TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE
,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','LCA0002300000802','TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE,
SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','LCA0002300000803','TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE,
SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','LCA0002300000804','TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE
,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','SYSTEM010000000D','TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE,
SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','SYSTEM010000001A','TESTDATA00000001',getdate(),1)

GO

INSERT INTO IW_TABLE_RULE_OUTPUT_FIELD (IW_TABLE_RULE_KEY,IW_OUTPUT_FIELD_KEY,ENTERED_BY,ENTRY_DATE,
SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','SYSTEM0100000024','TESTDATA00000001',getdate(),1)

GO
INSERT INTO IW_TABLE_RULE_RELATED_FIELD
(IW_TABLE_RULE_KEY,IW_COLUMN_TYPE_KEY,RELATIONSHIP,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','LCA0002300000800',2,'TESTDATA00000001',getdate(),1)


GO

INSERT INTO IW_TABLE_RULE_RELATED_TABLE (IW_TABLE_RULE_KEY,TABLE_NAME,
RELATIONSHIP,ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('LCA0002300000800','Taxon_Occurrence',1,'TESTDATA00000001',getdate(),1)


GO

INSERT INTO USABLE_FIELD (USABLE_FIELD_KEY,TABLE_NAME,FIELD_NAME,FIELD_DESCRIPTION,FIELD_TYPE,
APPLY_TO,SELECTABLE,SORTABLE,FILTERABLE,CALCULATION_SQL) 
VALUES ('LCA0002300000900','SURVEY','TEMPORARY_SURVEY','Survey Temporary','BOOLEAN',
'A',-1,-1,-1,'SURVEY.TEMPORARY_SURVEY')

GO

/****** Object:  UserDefinedFunction [dbo].[ConsolidateDeterminer]    Script Date: 11/12/2018 12:29:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*===========================================================================*\
  Description:	Returns the Determiner in the normal way unless allocated to 
  'Withheld'. In which case it returns the unparrsed determiner from the 
  Taxon Occurrence, Private Table. If this is null then uses the unparsed 
  Recorder from  the sample.
  
 
  Parameters:
  @TOCCKey  - Taxon_Occurrence_Key 
 		  
  Created:	September 2013
  Author: MikeWeideli 

\*=========================================================================== */

CREATE FUNCTION [dbo].[ConsolidateDeterminer]
(@TOCCKey char(16) )

RETURNS varchar(200)
AS
BEGIN

--****************************************************************************************************
DECLARE @ReturnString varchar(200)


Select @ReturnString =  dbo.FormatIndividual(INDIVIDUAL.TITLE, INDIVIDUAL.INITIALS,
INDIVIDUAL.FORENAME, INDIVIDUAL.SURNAME) FROM Taxon_Determination TDET 
INNER JOIN INDIVIDUAL ON INDIVIDUAL.NAME_KEY = TDET.DETERMINER 
WHERE TDET.DETERMINER <> 'LCA0002400000001' AND 
TDET.PREFERRED = 1 AND TDET.TAXON_OCCURRENCE_KEY = @TOCCKEY
   


If  @ReturnString IS NULL  SELECT @ReturnString = Detail FROM
Taxon_Private_data WHERE Taxon_Private_Data_Key = 'R6TEAM1800000002' 
AND Taxon_Private_Data.Taxon_Occurrence_key = @ToccKey  


If  @ReturnString IS NULL SELECT  @ReturnString = [dbo].[FormatEventRecorders](TOCC.SAMPLE_KEY)
FROM TAXON_OCCURRENCE TOCC WHERE TOCC.Taxon_Occurrence_Key = @TOCCKey

    
    

RETURN @ReturnString

END

GO

GRANT EXECUTE ON dbo.ConsolidateDeterminer TO PUBLIC

GO

INSERT INTO REPORT_ATTRIBUTE (REPORT_ATTRIBUTE_KEY, ITEM_NAME,ITEM_GROUP,SOURCE_TABLE,ATTRIBUTE_SQL,
REPORT_JOIN_KEY,REPORT_WHERE_KEY, ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA)
VALUES ('R6TEAM0100000003','Consolidated Determiners','Taxon\Observations\Determination','TAXON_OCCURRENCE',
'#REPORT_OUTPUT.[Consolidated Determiners] = dbo.ConsolidateDeterminer(TAXON_OCCURRENCE.TAXON_OCCURRENCE_KEY)',
'NBNSYS0000000016','NBNSYS0000000000','TESTDATA00000001',getdate(),1)

GO

INSERT INTO REPORT_FIELD (REPORT_FIELD_KEY,REPORT_ATTRIBUTE_KEY,FIELD_ITEM_NAME,FIELD_TYPE,FIELD_SIZE,
ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA) 
VALUES ('R6TEAM0100000003','R6TEAM0100000003','Consolidated Determiners','varchar',200,'TESTDATA00000001',getdate(),1) 


