SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
GO

/*============================================================================*\
	Mantis 484: Sample Ref and Surveyors Ref Filters not working  
\*============================================================================*/
 


DELETE FROM USABLE_FIELD
WHERE USABLE_FIELD_KEY = 'ABABABAB00000200'
AND EXISTS(SELECT * FROM USABLE_FIELD WHERE USABLE_FIELD_KEY = 'ABABABAB00000200')

GO


INSERT INTO USABLE_FIELD(USABLE_FIELD_KEY,TABLE_NAME,FIELD_NAME,FIELD_DESCRIPTION,
FIELD_TYPE,APPLY_TO,SELECTABLE,SORTABLE,FILTERABLE,CALCULATION_SQL)
VALUES ('ABABABAB00000200','SAMPLE','SAMPLE_REFERENCE','Sample Ref',
'TEXT','F',0,0,0,'SELECT Sample_Key AS ItemKey FROM Sample WHERE Sample_Reference')



DELETE FROM USABLE_FIELD
WHERE USABLE_FIELD_KEY = 'ABABABAB00000300'
AND EXISTS(SELECT * FROM USABLE_FIELD WHERE USABLE_FIELD_KEY = 'ABABABAB00000300')

GO


INSERT INTO USABLE_FIELD(USABLE_FIELD_KEY,TABLE_NAME,FIELD_NAME,FIELD_DESCRIPTION,
FIELD_TYPE,APPLY_TO,SELECTABLE,SORTABLE,FILTERABLE,CALCULATION_SQL)
VALUES ('ABABABAB00000300','TAXON_OCCURRENCE','SURVEYORS_REF','Surveyors Ref',
'TEXT','F',0,0,0,'SELECT Taxon_Occurrence_Key AS ItemKey FROM Taxon_Occurrence WHERE Surveyors_Ref')