/****** Set up a hierarchy for Taxon in Report Wizard to break it up  ******/
Update Report_Attribute set item_group = 'Taxon\Attributes'
where Report_Attribute_Key = 'LCA0002200000005'
Update Report_Attribute set item_group = 'Taxon\Attributes' 
where Report_Attribute_Key = 'LCA0002200000006'
Update Report_Attribute set item_group = 'Taxon\Authority' 
where Report_Attribute_Key = 'NBNSYS0000000072'
Update Report_Attribute set item_group = 'Taxon\Authority' 
where Report_Attribute_Key = 'LCA0002200000700'
Update Report_Attribute set item_group = 'Taxon\Checklist' 
where Report_Attribute_Key = 'NBNSYS0000000069'
Update Report_Attribute set item_group = 'Taxon\Hierarchy' 
where Report_Attribute_Key = 'NBNSYS0000000088'
Update Report_Attribute set item_group = 'Taxon\Hierarchy' 
where Report_Attribute_Key = 'SRA0000400000023'
Update Report_Attribute set item_group = 'Taxon\Hierarchy' 
where Report_Attribute_Key = 'SRA0000400000024'
Update Report_Attribute set item_group = 'Taxon\Hierarchy' 
where Report_Attribute_Key = 'SRA0000400000025'
Update Report_Attribute set item_group = 'Taxon\Hierarchy' 
where Report_Attribute_Key = 'SRA0000400000026'
Update Report_Attribute set item_group = 'Taxon\Hierarchy' 
where Report_Attribute_Key = 'SRA0000400000027'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'JNCCDEV100000015'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'LCA0002200000001'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'LCA0002200000002'
pdate Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'LCA0002200000003'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'LCA0002200000004'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'LCA0002200000007'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'LCA0002200000008'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'NBNSYS0000000070'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'NBNSYS0000000071'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'NBNSYS0000000073'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'NBNSYS0000000086'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'SRA0000400000028'
Update Report_Attribute set item_group = 'Taxon\Name' 
where Report_Attribute_Key = 'SRA0000400000029'

Update Report_Attribute set item_group = 'Taxon\Specimen' 
where Report_Attribute_Key = 'NBNSYS0000000066'
Update Report_Attribute set item_group = 'Taxon\Specimen' 
where Report_Attribute_Key = 'NBNSYS0000000067'
Update Report_Attribute set item_group = 'Taxon\Specimen' 
where Report_Attribute_Key = 'NBNSYS0000000068'
Update Report_Attribute set item_group = 'Taxon\Specimen' 
where Report_Attribute_Key = 'NBNSYS0000000167'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000075'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000076'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000078'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000079'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000080'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000089'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008A'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008B'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008C'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008D'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008E'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008F'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008G'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008H'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008I'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008J'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008K'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008L'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008M'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008N'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008O'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008P'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008Q'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008R'



Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008S'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008T'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000008U'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009C'



Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009D'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009E'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009F'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009G'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009H'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009I'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009J'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009K'



Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009L'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009M'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009N'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009O'



Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009P'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009Q'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009R'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009S'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009T'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009U'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009V'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009W'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009X'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009Y'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS000000009Z'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A0'



Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A1'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A2'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A3'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A4'




Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A5'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A6'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A7'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A8'




Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000A9'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B0'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B1'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B2'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B3'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B4'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B5'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B6'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B7'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B8'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS00000000B9'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000100'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000101'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000102'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000102'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000104'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000105'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000106'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000107'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000108'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000109'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000110'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000111'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000112'


Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000113'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000114'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000115'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000116'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000117'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000118'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000119'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000120'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000121'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000122'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000123'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000124'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000125'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000126'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000127'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000128'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000129'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000130'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000131'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000132'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000133'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000134'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000135'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000136'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000137'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000138'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000139'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000140'


Update Report_Attribute set item_group = 'TTaxon\Status' 
where ReporUpdate Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000136'
t_Attribute_Key = 'NBNSYS0000000136'

Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000141'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000142'
Update Report_Attribute set item_group = 'Taxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000143'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000144'

Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000145'
Update Report_Attribute set item_group = 'TTaxon\Status' 
where Report_Attribute_Key = 'NBNSYS0000000146'


