USE NBNData
-- Ensure collation sequence is correct
ALTER TABLE TAXON_VERSION DROP CONSTRAINT [TAXON_VERSION_CHK_VALIDATION_LEVEL]

ALTER TABLE SAMPLE DROP CONSTRAINT [CK_SAMPLE_CHK_OUTSTANDING_CARD]

USE MASTER
ALTER DATABASE NBNData COLLATE SQL_Latin1_General_CP1_CI_AS
USE NBNData

ALTER TABLE [dbo].[TAXON_VERSION]
ADD CONSTRAINT [TAXON_VERSION_CHK_VALIDATION_LEVEL] CHECK ([VALIDATION_LEVEL] like '[0-3]')

ALTER TABLE [dbo].[SAMPLE] ADD 
	CONSTRAINT [CK_SAMPLE_CHK_OUTSTANDING_CARD] CHECK ([OUTSTANDING_CARD] like '[0-2]')