/***** Populate private_Type and transfer to new tables *****/

INSERT INTO TAXON_PRIVATE_TYPE (TAXON_PRIVATE_TYPE_KEY,SHORT_NAME,LONG_NAME,
ENTERED_BY,ENTRY_DATE,SYSTEM_SUPPLIED_DATA,
DESCRIPTION)
VALUES('R6TEAM1800000001','External Ref','External Reference','TESTDATA00000001',GetDate(),1,
'External Reference Item_Name holds the owner/source and Detail
the key of the external reference')

GO

INSERT INTO TAXON_PRIVATE_DATA(TAXON_PRIVATE_DATA_KEY, 
TAXON_PRIVATE_TYPE_KEY,TAXON_OCCURRENCE_KEY,ITEM_NAME,DETAIL,
ENTRY_DATE,ENTERED_BY,ITEM_DATE)
SELECT TAXON_OCCURRENCE_EXT_REF_KEY,'R6TEAM1800000001',TAXON_OCCURRENCE_KEY,
'None',EXTERNAL_KEY,
DATE_IMPORTED,'TESTDATA00000001',DATE_IMPORTED FROM TAXON_OCCURRENCE_EXT_REF


GO

if not exists (SELECT * from LAST_KEY WHERE 
  TABLE_NAME = 'TAXON_PRIVATE_DATA') 
INSERT INTO LAST_KEY VALUES('TAXON_PRIVATE_DATA','00000000')
 
UPDATE LAST_KEY SET LAST_KEY_TEXT  = LK.LAST_KEY_TEXT 
FROM LAST_KEY,LAST_KEY LK WHERE LK.TABLE_NAME = 'TAXON_OCCURRENCE_EXT_REF'
AND LAST_KEY.TABLE_NAME = 'TAXON_PRIVATE_DATA'

GO

INSERT INTO TERM_LIST ([TABLE],KEY_FIELD,DESCRIPTION,SYSTEM_SUPPLIED_DATA 
)
VALUES ('TAXON_PRIVATE_TYPE','TAXON_PRIVATE_TYPE_KEY','Taxon Private Type'
,1) 