--Ensure Preferred determiner picked up by the report wizard
UPDATE Report_Join
SET Join_SQL='FROM #REPORT_OUTPUT LEFT JOIN  TAXON_DETERMINATION ON #REPORT_OUTPUT.OCCURRENCE_KEY = TAXON_DETERMINATION.TAXON_OCCURRENCE_KEY AND TAXON_DETERMINATION.PREFERRED=1 LEFT JOIN  NAME ON TAXON_DETERMINATION.DETERMINER = NAME.NAME_KEY LEFT JOIN  INDIVIDUAL ON NAME.NAME_KEY = INDIVIDUAL.NAME_KEY'
WHERE Report_Join_Key='NBNSYS0000000021'


