/****** Object:  View [dbo].[LC_SAMP_ADMIN_FILTER]    Script Date: 14/09/2015 13:18:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[LC_SAMP_ADMIN_FILTER]
AS
SELECT SAA.SAMPLE_KEY,ITEM_NAME
FROM SAMPLE_ADMIN_AREAS SAA
INNER JOIN ADMIN_AREA
ON ADMIN_AREA.ADMIN_AREA_KEY = SAA.ADMIN_AREA_KEY 
          

GO

GRANT SELECT ON [dbo].[LC_SAMP_ADMIN_FILTER] TO PUBLIC

GO 
Insert Into USABLE_TABLE (USABLE_TABLE_KEY,TABLE_NAME,LInK_TABLE,LINK,APPLY_TO,JOIN_ORDER)
VALUES ('LCA0002500000006','LC_SAMP_ADMIN_FILTER','Sample','LC_SAMP_ADMIN_FILTER.Sample_Key =Sample.Sample_Key','T',10)

GO
INSERT INTO USABLE_FIELD(USABLE_FIELD_KEY,TABLE_NAME,FIELD_NAME, FIELD_DESCRIPTION,FIELD_TYPE,APPLY_TO,SELECTABLE,
SORTABLE,FILTERABLE,CALCULATION_SQL)
VALUES ('LCA0002500000006','LC_SAMP_ADMIN_FILTER','Item_Name','Admin. Area Name','TEXT','T',0,0,1,'LC_SAMP_ADMIN_FILTER.Item_Name')
