-- updates to allow a concatenated field containing abundance data to be included in the report wizard
-- Script created by Mike Weideli and Steve Wilkinson

-- delete the rows first
DELETE FROM REPORT_FIELD WHERE REPORT_FIELD_KEY = 'JNCCDEV100000016';
DELETE FROM REPORT_ATTRIBUTE WHERE REPORT_ATTRIBUTE_KEY = 'JNCCDEV100000014';

INSERT INTO REPORT_ATTRIBUTE ( REPORT_ATTRIBUTE_KEY, ITEM_GROUP, SOURCE_TABLE, ITEM_NAME, ATTRIBUTE_SQL, REPORT_JOIN_KEY, REPORT_WHERE_KEY, ENTERED_BY, SYSTEM_SUPPLIED_DATA ) SELECT 'JNCCDEV100000014' AS Expr0, 'Observation'  AS Expr1,  'OBSERVATION' AS Expr2, 'Obs Abundances (LC)' AS Expr3, '#REPORT_OUTPUT.[Obs Abundances (LC)] = dbo.LCFormatAbundanceData(TAXON_OCCURRENCE_KEY)' AS Expr4, 'NBNSYS0000000016' AS Expr5, 'NBNSYS0000000000' AS Expr6, 'TESTDATA00000001' AS Expr7, 1 as Expr8

INSERT INTO REPORT_FIELD ( REPORT_FIELD_KEY, REPORT_ATTRIBUTE_KEY, FIELD_ITEM_NAME, FIELD_TYPE, FIELD_SIZE, ENTERED_BY, SYSTEM_SUPPLIED_DATA ) SELECT  'JNCCDEV100000016' AS Expr0, 'JNCCDEV100000014'  AS Expr1, 'Obs Abundances (LC)' AS Expr2, 'varchar' AS Expr3, 8000 AS Expr4, 'TESTDATA00000001' as exp5, 1 as expr6
