GRANT UPDATE ON Taxon_Occurrence_Ext_Ref to R2K_FullEdit
GRANT DELETE ON Taxon_Occurrence_Ext_Ref to R2K_FullEdit
GRANT INSERT ON Taxon_Occurrence_Ext_Ref to R2K_FullEdit

GRANT SELECT ON IW_Matched_Abundance_Qualifiers TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Abundance_Qualifiers TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Abundance_Qualifiers TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Abundance_Qualifiers TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Associated_Species TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Associated_Species TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Associated_Species TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Associated_Species TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Association_Types TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Association_Types TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Association_Types TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Association_Types TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Biotopes TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Biotopes TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Biotopes TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Biotopes TO R2K_FULLEDIT


GRANT SELECT ON IW_Matched_Determination_Types TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Determination_Types TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Determination_Types TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Determination_Types TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Determiner_Roles TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Determiner_Roles TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Determiner_Roles TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Determiner_Roles TO R2K_FULLEDIT


GRANT SELECT ON IW_Matched_Locations TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Locations TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Locations TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Locations TO R2K_FULLEDIT


GRANT SELECT ON IW_Matched_Names TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Names TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Names TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Names TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Record_Types TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Record_Types TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Record_Types TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Record_Types TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_References TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_References TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_References TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_References TO R2K_FULLEDIT


GRANT SELECT ON IW_Matched_Sample_Types TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Sample_Types TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Sample_Types TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Sample_Types TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Species TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Species TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Species TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Species TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Specimen_Types TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Specimen_Types TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Specimen_Types TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Specimen_Types TO R2K_FULLEDIT

GRANT SELECT ON IW_Matched_Substrates TO R2K_FULLEDIT
GRANT UPDATE ON IW_Matched_Substrates TO R2K_FULLEDIT
GRANT DELETE ON IW_Matched_Substrates TO R2K_FULLEDIT
GRANT INSERT ON IW_Matched_Substrates TO R2K_FULLEDIT

