/*

 Change the SPATIAL_REF_SYSTEM field type to VARCHAR(4) from a CHAR(10).

 $History: 00000001.sql $
 * 
 * *****************  Version 3  *****************
 * User: Johnvanbreda Date: 2/06/03    Time: 13:52
 * Updated in $/JNCC/Development/Build/SQL Scripts/Upgrade Scripts/Sequenced
 * Added try comments to each drop constraint batch
 * 
 * *****************  Version 2  *****************
 * User: Johnvanbreda Date: 25/04/03   Time: 14:21
 * Updated in $/JNCC/Development/Build/SQL Scripts/Upgrade Scripts/Sequenced
 * Also fixed up the report field
 * 
 * *****************  Version 1  *****************
 * User: Ericsalmon   Date: 11/04/03   Time: 15:39
 * Created in $/JNCC/Development/Build/SQL Scripts/Upgrade Scripts/Sequenced

*/

USE NBNData
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE
	DROP CONSTRAINT FK_SAMPLE_SAMPLE_TYPE
GO
--try
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE
	DROP CONSTRAINT FK_SAMPLE_LOCATION
GO
--try
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE
	DROP CONSTRAINT FK_SAMPLE_SURVEY_EVENT
GO
--try
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE
	DROP CONSTRAINT DF__Temporary__OUTST__73852659
GO
--try
ALTER TABLE dbo.SAMPLE
	DROP CONSTRAINT DF__Temporary__ENTRY__74794A92
GO
CREATE TABLE dbo.Tmp_SAMPLE
	(
	SAMPLE_KEY char(16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SAMPLE_REFERENCE varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VAGUE_DATE_START int NULL,
	VAGUE_DATE_END int NULL,
	VAGUE_DATE_TYPE varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SPATIAL_REF varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SPATIAL_REF_SYSTEM varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LAT float(53) NULL,
	LONG float(53) NULL,
	DURATION varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME] datetime NULL,
	OUTSTANDING_CARD tinyint NOT NULL,
	SPATIAL_REF_QUALIFIER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SAMPLE_TYPE_KEY char(16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LOCATION_KEY char(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SURVEY_EVENT_KEY char(16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	COMMENT text COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RECORDERS varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ENTERED_BY char(16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ENTRY_DATE smalldatetime NOT NULL,
	CHANGED_BY char(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CHANGED_DATE smalldatetime NULL,
	LOCATION_NAME varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUSTODIAN char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_SAMPLE ADD CONSTRAINT
	DF__Temporary__OUTST__73852659 DEFAULT (0) FOR OUTSTANDING_CARD
GO
ALTER TABLE dbo.Tmp_SAMPLE ADD CONSTRAINT
	DF__Temporary__ENTRY__74794A92 DEFAULT (getdate()) FOR ENTRY_DATE
GO
IF EXISTS(SELECT * FROM dbo.SAMPLE)
	 EXEC('INSERT INTO dbo.Tmp_SAMPLE (SAMPLE_KEY, SAMPLE_REFERENCE, VAGUE_DATE_START, VAGUE_DATE_END, VAGUE_DATE_TYPE, SPATIAL_REF, SPATIAL_REF_SYSTEM, LAT, LONG, DURATION, [TIME], OUTSTANDING_CARD, SPATIAL_REF_QUALIFIER, SAMPLE_TYPE_KEY, LOCATION_KEY, SURVEY_EVENT_KEY, COMMENT, RECORDERS, ENTERED_BY, ENTRY_DATE, CHANGED_BY, CHANGED_DATE, LOCATION_NAME, CUSTODIAN)
		SELECT SAMPLE_KEY, SAMPLE_REFERENCE, VAGUE_DATE_START, VAGUE_DATE_END, VAGUE_DATE_TYPE, SPATIAL_REF, CONVERT(varchar(4), SPATIAL_REF_SYSTEM), LAT, LONG, DURATION, [TIME], OUTSTANDING_CARD, SPATIAL_REF_QUALIFIER, SAMPLE_TYPE_KEY, LOCATION_KEY, SURVEY_EVENT_KEY, COMMENT, RECORDERS, ENTERED_BY, ENTRY_DATE, CHANGED_BY, CHANGED_DATE, LOCATION_NAME, CUSTODIAN FROM dbo.SAMPLE TABLOCKX')
GO
ALTER TABLE dbo.TAXON_OCCURRENCE
	DROP CONSTRAINT FK_TAXON_OCCURRENCE_SAMPLE
GO
ALTER TABLE dbo.SAMPLE_SOURCES
	DROP CONSTRAINT FK_SAMPLE_SOURCES_SAMPLE
GO
ALTER TABLE dbo.BIOTOPE_OCCURRENCE
	DROP CONSTRAINT FK_BIOTOPE_OCCURRENCE_SAMPLE
GO
ALTER TABLE dbo.SAMPLE_DATA
	DROP CONSTRAINT FK_SAMPLE_DATA_SAMPLE
GO
ALTER TABLE dbo.SAMPLE_RECORDER
	DROP CONSTRAINT FK_SAMPLE_RECORDER_SAMPLE
GO
ALTER TABLE dbo.SAMPLE_RELATION
	DROP CONSTRAINT FK_SAMPLE_RELATION_SAMPLE1
GO
ALTER TABLE dbo.SAMPLE_RELATION
	DROP CONSTRAINT FK_SAMPLE_RELATION_SAMPLE2
GO
DROP TABLE dbo.SAMPLE
GO
EXECUTE sp_rename N'dbo.Tmp_SAMPLE', N'SAMPLE', 'OBJECT'
GO
ALTER TABLE dbo.SAMPLE ADD CONSTRAINT
	PK_SAMPLE PRIMARY KEY NONCLUSTERED 
	(
	SAMPLE_KEY
	) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX IX_SURVEY_EVENT_KEY ON dbo.SAMPLE
	(
	SURVEY_EVENT_KEY
	) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX LOCATION_KEY ON dbo.SAMPLE
	(
	LOCATION_KEY
	) ON [PRIMARY]
GO
ALTER TABLE dbo.SAMPLE WITH NOCHECK ADD CONSTRAINT
	CK_SAMPLE_CHK_OUTSTANDING_CARD CHECK (([OUTSTANDING_CARD] like '[0-2]'))
GO
ALTER TABLE dbo.SAMPLE WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_SURVEY_EVENT FOREIGN KEY
	(
	SURVEY_EVENT_KEY
	) REFERENCES dbo.SURVEY_EVENT
	(
	SURVEY_EVENT_KEY
	)
GO
ALTER TABLE dbo.SAMPLE WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_LOCATION FOREIGN KEY
	(
	LOCATION_KEY
	) REFERENCES dbo.LOCATION
	(
	LOCATION_KEY
	)
GO
ALTER TABLE dbo.SAMPLE WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_SAMPLE_TYPE FOREIGN KEY
	(
	SAMPLE_TYPE_KEY
	) REFERENCES dbo.SAMPLE_TYPE
	(
	SAMPLE_TYPE_KEY
	)
GO
CREATE TRIGGER SAMPLECustodianInsert ON dbo.SAMPLE AFTER INSERT AS UPDATE SAMPLE SET SAMPLE.CUSTODIAN = SUBSTRING(SAMPLE.SAMPLE_KEY, 1, 8) FROM SAMPLE INNER JOIN INSERTED ON SAMPLE.SAMPLE_KEY = INSERTED.SAMPLE_KEY WHERE SAMPLE.CUSTODIAN IS NULL
GO
GRANT SELECT ON dbo.SAMPLE TO R2k_ReadOnly  AS dbo
GRANT SELECT ON dbo.SAMPLE TO R2k_RecordCardsOnly  AS dbo
GRANT INSERT ON dbo.SAMPLE TO R2k_RecordCardsOnly  AS dbo
GRANT DELETE ON dbo.SAMPLE TO R2k_RecordCardsOnly  AS dbo
GRANT SELECT ON dbo.SAMPLE TO R2k_AddOnly  AS dbo
GRANT INSERT ON dbo.SAMPLE TO R2k_AddOnly  AS dbo
GRANT DELETE ON dbo.SAMPLE TO R2k_AddOnly  AS dbo
GRANT SELECT ON dbo.SAMPLE TO R2k_FullEdit  AS dbo
GRANT UPDATE ON dbo.SAMPLE TO R2k_FullEdit  AS dbo
GRANT INSERT ON dbo.SAMPLE TO R2k_FullEdit  AS dbo
GRANT DELETE ON dbo.SAMPLE TO R2k_FullEdit  AS dbo
GRANT SELECT ON dbo.SAMPLE TO R2k_Administrator  AS dbo
GRANT UPDATE ON dbo.SAMPLE TO R2k_Administrator  AS dbo
GRANT INSERT ON dbo.SAMPLE TO R2k_Administrator  AS dbo
GRANT DELETE ON dbo.SAMPLE TO R2k_Administrator  AS dbo
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE_RELATION WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_RELATION_SAMPLE1 FOREIGN KEY
	(
	SAMPLE_KEY_1
	) REFERENCES dbo.SAMPLE
	(
	SAMPLE_KEY
	)
GO
ALTER TABLE dbo.SAMPLE_RELATION WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_RELATION_SAMPLE2 FOREIGN KEY
	(
	SAMPLE_KEY_2
	) REFERENCES dbo.SAMPLE
	(
	SAMPLE_KEY
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE_RECORDER WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_RECORDER_SAMPLE FOREIGN KEY
	(
	SAMPLE_KEY
	) REFERENCES dbo.SAMPLE
	(
	SAMPLE_KEY
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE_DATA WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_DATA_SAMPLE FOREIGN KEY
	(
	SAMPLE_KEY
	) REFERENCES dbo.SAMPLE
	(
	SAMPLE_KEY
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.BIOTOPE_OCCURRENCE WITH NOCHECK ADD CONSTRAINT
	FK_BIOTOPE_OCCURRENCE_SAMPLE FOREIGN KEY
	(
	SAMPLE_KEY
	) REFERENCES dbo.SAMPLE
	(
	SAMPLE_KEY
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.SAMPLE_SOURCES WITH NOCHECK ADD CONSTRAINT
	FK_SAMPLE_SOURCES_SAMPLE FOREIGN KEY
	(
	SAMPLE_KEY
	) REFERENCES dbo.SAMPLE
	(
	SAMPLE_KEY
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TAXON_OCCURRENCE WITH NOCHECK ADD CONSTRAINT
	FK_TAXON_OCCURRENCE_SAMPLE FOREIGN KEY
	(
	SAMPLE_KEY
	) REFERENCES dbo.SAMPLE
	(
	SAMPLE_KEY
	)
GO
COMMIT

--Also update the report field
UPDATE REPORT_FIELD 
SET FIELD_TYPE='varchar',
    FIELD_SIZE=4 
WHERE REPORT_FIELD_KEY='NBNSYS0000000028'
