INSERT INTO SURVEY_MEDIA (SURVEY_MEDIA_KEY, SHORT_NAME, LONG_NAME, [DESCRIPTION], ENTERED_BY, ENTRY_DATE, SYSTEM_SUPPLIED_DATA)
VALUES ('NBNSYS0000000007', 'Temporary', 'Temporary', 'Temporary records which are not included in exports.', 'NBNSYS0000000001', GETDATE(), 1);

DELETE FROM SETTING WHERE [NAME] = 'TempMedia'
INSERT INTO SETTING VALUES ('TempMedia ', 'NBNSYS0000000007');

UPDATE [Sample] SET Recorders=null
