/****** Object:  UserDefinedFunction [dbo].[ufn_ReturnReviewStatus]    Script Date: 01/14/2020 16:30:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER FUNCTION [dbo].[ufn_ReturnReviewStatus] 
(@TOCCKey char(16))
RETURNS char(1)

AS
BEGIN
Declare @Competency integer
Declare @ReviewStatus char(1)
Declare @maxDate varchar(30) 
Declare @maxDate2 varchar(30)

Set @Competency = (Select CAST([DATA] AS INT)  FROM SETTING 
                   WHERE [NAME] = 'Competency')

IF @Competency > 0 

BEGIN

  Set @ReviewStatus = '2'

  SET @maxDate = (SELECT MAX(Str(TDET2.VAGUE_DATE_START)+ TDET2.TAXON_DETERMINATION_KEY)
    FROM TAXON_DETERMINATION TDET2 WHERE TDET2.TAXON_OCCURRENCE_KEY = @TOCCKey)
  SET @MaxDate2 = (SELECT MAX(Str(TDET3.VAGUE_DATE_START)+ TDET3.TAXON_DETERMINATION_KEY)
    FROM TAXON_DETERMINATION TDET3 INNER JOIN DETERMINER_ROLE DR
    ON DR.DETERMINER_ROLE_KEY = TDET3.DETERMINER_ROLE_KEY AND
    DR.VALIDATION_COMPETENCY >= @COMPETENCY 
    WHERE TDET3.TAXON_OCCURRENCE_KEY = @TOCCKey) 

  IF NOT EXISTS (SELECT * FROM TAXON_DETERMINATION TDET 
    INNER JOIN DETERMINER_ROLE DR ON DR.DETERMINER_ROLE_KEY =
    TDET.DETERMINER_ROLE_KEY WHERE TDET.TAXON_OCCURRENCE_KEY = @TOCCKey
    AND DR.VALIDATION_COMPETENCY >= @Competency AND  
    Str(TDET.VAGUE_DATE_START)+ TDET.TAXON_DETERMINATION_KEY =  
    @maxDate) SET @ReviewStatus = 1
  ELSE
    IF EXISTS (SELECT * FROM TAXON_DETERMINATION TDET INNER JOIN
      TAXON_DETERMINATION TDET2 ON TDET2.TAXON_OCCURRENCE_KEY = TDET.TAXON_OCCURRENCE_KEY
      AND TDET.PREFERRED = 1 AND TDET2.TAXON_OCCURRENCE_KEY = @TOCCKey
      INNER JOIN DETERMINATION_TYPE TDT ON TDT.DETERMINATION_TYPE_KEY =
      TDET.DETERMINATION_TYPE_KEY INNER JOIN DETERMINATION_TYPE TDT2 ON TDT2.DETERMINATION_TYPE_KEY =
      TDET2.DETERMINATION_TYPE_KEY   
      WHERE Str(TDET2.VAGUE_DATE_START)+ TDET2.TAXON_DETERMINATION_KEY =  
      @MaxDate2
      AND TDET2.VAGUE_DATE_START >= TDET.VAGUE_DATE_START 
      AND (TDT2.VERIFIED = 2 OR TDT.VERIFIED = TDT2.VERIFIED OR 
      (TDT2.VERIFIED = 0 AND TDT.VERIFIED = 1)) 
      AND  TDET.TAXON_LIST_ITEM_KEY  =
      TDET2.TAXON_LIST_ITEM_KEY)
      SET @ReviewStatus = '3'  
 

END


Return @ReviewStatus

END
