UPDATE Report_Attribute
SET Attribute_SQL='#REPORT_OUTPUT.[Sample Month] = 
	CASE WHEN SAMPLE.VAGUE_DATE_TYPE IN (''P'', ''Y'', ''YY'', ''Y-'', ''Y'', ''S'', ''U'') THEN NULL
	WHEN SAMPLE.VAGUE_DATE_START IS NULL THEN NULL
	WHEN SAMPLE.VAGUE_DATE_END IS NULL THEN NULL
ELSE dbo.FormatDatePart(SAMPLE.VAGUE_DATE_START, SAMPLE.VAGUE_DATE_END, SAMPLE.VAGUE_DATE_TYPE, 1) END'
WHERE Report_Attribute_Key='NBNSYS0000000047'


