Delete From USABLE_FIELD 
Where Exists (Select * From USABLE_FIELD Where USABLE_FIELD_KEY = 'ABABABAB00000036') and USABLE_FIELD_KEY = 'ABABABAB00000036'

GO

Insert Into USABLE_FIELD
Values ('ABABABAB00000036', 'SAMPLE_TYPE', 'SHORT_NAME', 'Sample Type', 'TEXT', 'A', 1, 1, 1, 'SAMPLE_TYPE.SHORT_NAME')

GO


DELETE FROM USABLE_TABLE
WHERE EXISTS(SELECT * FROM USABLE_TABLE WHERE USABLE_TABLE_KEY = 'ABABABAB00000070') AND USABLE_TABLE_KEY = 'ABABABAB00000070'

GO

INSERT INTO USABLE_TABLE(USABLE_TABLE_KEY,TABLE_NAME,LINK_TABLE,LINK,APPLY_TO,JOIN_ORDER)
VALUES ('ABABABAB00000070', 'Sample_Type','Sample',
'Sample_Type.Sample_Type_Key = Sample.Sample_Type_Key','A',5)


GO

UPDATE USABLE_FIELD SET APPLY_TO = 'T' WHERE USABLE_FIELD_KEY = 'JNCCDEV100000028'

 