/****** Include User Added Taxa in the Virtual_Organism_Table  ******/
/****** Object:  StoredProcedure [dbo].[usp_Virtual_Organism_Populate]    Script Date: 01/22/2020 09:41:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*===========================================================================*\
  Description:	
			Procedure which populates the Virtual Organism Table 
			
		    Created:	August 2019 Mike Weideli

            Revised:    January 2020 for User Added Taxa
   ===========================================================================*/
ALTER PROCEDURE [dbo].[usp_Virtual_Organism_Populate] 

AS 

TRUNCATE TABLE VIRTUAL_ORGANISM 

INSERT INTO VIRTUAL_ORGANISM
    ([TAXON_LIST_ITEM_KEY],
	[TAXON_LIST_VERSION_KEY],
	[TAXON_VERSION_KEY],
	[PREFERRED_NAME],
	[TAXON_LIST_VERSION_TO],
	[Sort_Code] ,
	[PARENT],
	[TAXON_RANK_KEY],
	[ENTERED_BY],
	[ENTRY_DATE],
	[SYSTEM_SUPPLIED_DATA],
	[Has_Children])
 
	SELECT NS.RECOMMENDED_TAXON_LIST_ITEM_KEY AS TAXON_LIST_ITEM_KEY,
	       'VIRTUAL_ORGANISM' 	AS TAXON_LIST_VERSION_KEY, NS.RECOMMENDED_TAXON_VERSION_KEY         
           AS TAXON_VERSION_KEY, NS.RECOMMENDED_TAXON_LIST_ITEM_KEY AS PREFERRED_NAME, NULL AS         
           TAXON_LIST_VERSION_TO, O.Sort_Code, NS2.RECOMMENDED_TAXON_LIST_ITEM_KEY AS PARENT, 
           O.ORGANISM_RANK_KEY AS TAXON_RANK_KEY, O.ENTERED_BY, O.ENTRY_DATE, 	        
           O.SYSTEM_SUPPLIED_DATA, O.Has_Children
	       FROM dbo.ORGANISM AS O INNER JOIN
             NAMESERVER AS NS ON O.TAXON_VERSION_KEY = NS.INPUT_TAXON_VERSION_KEY AND         
             NS.RECOMMENDED_TAXON_VERSION_KEY = 
	         NS.INPUT_TAXON_VERSION_KEY
             AND O.REDUNDANT_FLAG IS NULL               
             INNER JOIN
             dbo.ORGANISM AS O2 ON O2.ORGANISM_KEY = O.PARENT_KEY INNER JOIN
             dbo.NAMESERVER AS NS2 ON O2.TAXON_VERSION_KEY = 	NS2.INPUT_TAXON_VERSION_KEY 
             AND NS.RECOMMENDED_TAXON_VERSION_KEY = 	NS.INPUT_TAXON_VERSION_KEY
	UNION
	SELECT NS.RECOMMENDED_TAXON_LIST_ITEM_KEY AS TAXON_LIST_ITEM_KEY,
           'VIRTUAL_ORGANISM' AS TAXON_LIST_VERSION_KEY, NS.RECOMMENDED_TAXON_VERSION_KEY AS   
           TAXON_VERSION_KEY,
           NS.RECOMMENDED_TAXON_LIST_ITEM_KEY, NULL AS TAXON_LIST_VERSION_TO, 	        
           O.Sort_Code, NULL AS PARENT, O.ORGANISM_RANK_KEY AS TAXON_RANK_KEY, O.ENTERED_BY, 
	       O.ENTRY_DATE, O.SYSTEM_SUPPLIED_DATA, O.Has_Children
	       FROM dbo.ORGANISM AS O INNER JOIN
              NAMESERVER AS NS ON O.TAXON_VERSION_KEY = NS.INPUT_TAXON_VERSION_KEY AND
              NS.RECOMMENDED_TAXON_VERSION_KEY = 
              NS.INPUT_TAXON_VERSION_KEY AND O.PARENT_KEY IS NULL 
    UNION 
    SELECT ITN.TAXON_LIST_ITEM_KEY AS TAXON_LIST_ITEM_KEY,
	       'VIRTUAL_ORGANISM' 	AS TAXON_LIST_VERSION_KEY, ITN.TAXON_VERSION_KEY         
           AS TAXON_VERSION_KEY, ITN.TAXON_LIST_ITEM_KEY AS PREFERRED_NAME, NULL AS         
           TAXON_LIST_VERSION_TO, O.Sort_Code, ITN2.RECOMMENDED_TAXON_LIST_ITEM_KEY AS PARENT, 
           O.ORGANISM_RANK_KEY AS TAXON_RANK_KEY, O.ENTERED_BY, O.ENTRY_DATE, 	        
           O.SYSTEM_SUPPLIED_DATA, O.Has_Children
	       FROM dbo.ORGANISM AS O INNER JOIN
             INDEX_TAXON_NAME ITN ON ITN.TAXON_VERSION_KEY = 
	         O.TAXON_VERSION_KEY AND O.SYSTEM_SUPPLIED_DATA = 0  
             AND O.REDUNDANT_FLAG IS NULL               
             INNER JOIN
             dbo.ORGANISM AS O2 ON O2.ORGANISM_KEY = O.PARENT_KEY INNER JOIN
             INDEX_TAXON_NAME ITN2 ON ITN2.TAXON_VERSION_KEY = O2.TAXON_VERSION_KEY    