IF NOT EXISTS(SELECT 1 FROM Database_Relationship WHERE Relationship_Key='NBNSYS000000004A')
INSERT INTO Database_Relationship
VALUES ('NBNSYS000000004A', 'TAXON_VERSIONNAMESERVER', 
		'TAXON_VERSION', 'TAXON_VERSION_KEY', 
		'NAMESERVER', 'INPUT_TAXON_VERSION_KEY', 
		0, 0)