/****** Changes to add report and filtering on non-native-flag  ******/


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NATIVE_VIEW]') AND type in (N'V'))
DROP PROCEDURE [dbo].[NATIVE_VIEW] 

GO

/****** Object:  View [dbo].[NATIVE_VIEW]    Script Date: 11/14/2016 17:18:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*===========================================================================*\
  Description:	VIEW which gets the Non_Native_Flag 
              
  Created:	November 2016
  Author: MikeWeideli

\*=========================================================================== */
CREATE VIEW [dbo].[NATIVE_VIEW]
AS
SELECT     TLI.TAXON_LIST_ITEM_KEY, CASE ISNULL(O.NON_NATIVE_FLAG, 'N') WHEN 'N' THEN 1 ELSE 0 END AS NATIVE
FROM         dbo.TAXON_LIST_ITEM AS TLI INNER JOIN
                      dbo.INDEX_TAXON_NAME AS ITN ON ITN.TAXON_LIST_ITEM_KEY = TLI.TAXON_LIST_ITEM_KEY INNER JOIN
                      dbo.TAXON_LIST_ITEM AS TLI2 ON TLI2.TAXON_LIST_ITEM_KEY = ITN.RECOMMENDED_TAXON_LIST_ITEM_KEY INNER JOIN
                      dbo.ORGANISM AS O ON O.TAXON_VERSION_KEY = TLI2.TAXON_VERSION_KEY

GO

GRANT SELECT ON [dbo].[NATIVE_VIEW] TO PUBLIC

GO

UPDATE REPORT_ATTRIBUTE SET ITEM_NAME = 'Taxon UK Native', SOURCE_TABLE = 'NATIVE_VIEW',
ATTRIBUTE_SQL = '#REPORT_OUTPUT.[Taxon UK Native] = NATIVE_VIEW.NATIVE'
WHERE REPORT_ATTRIBUTE_KEY = 'NBNSYS0000000080'

GO

UPDATE REPORT_FIELD  SET Field_Item_Name = 'Taxon UK Native', Field_Type ='bit'  
WHERE REPORT_FIELD_KEY = 'NBNSYS0000000080'

GO


UPDATE REPORT_JOIN SET JOIN_SQL =  'FROM #REPORT_OUTPUT
LEFT JOIN NATIVE_VIEW ON NATIVE_VIEW.TAXON_LIST_ITEM_KEY =  #REPORT_OUTPUT.LIST_ITEM_KEY'
WHERE REPORT_JOIN_KEY = 'NBNSYS0000000034'


GO

UPDATE USABLE_FIELD SET TABLE_NAME = 'NATIVE_VIEW', FIELD_NAME = 'NATIVE', FIELD_DESCRIPTION = 'Taxon is Native',
FIELD_TYPE = 'BOOLEAN', APPLY_TO = 'T', SELECTABLE = 1, SORTABLE = 1, FILTERABLE = 1, CALCULATION_SQL = 'NATIVE_VIEW.NATIVE'
WHERE USABLE_FIELD_KEY = 'ABABABAB00000043'


GO

DELETE FROM USABLE_TABLE WHERE USABLE_TABLE_KEY = 'LCA0002500000010'

GO

INSERT INTO USABLE_TABLE (USABLE_TABLE_KEY,TABLE_NAME,LINK_TABLE,LINK,APPLY_TO,JOIN_ORDER)
VALUES('LCA0002500000010','NATIVE_VIEW','Taxon_List_Item',
'NATIVE_VIEW.Taxon_List_Item_Key = Taxon_List_Item.Taxon_List_Item_Key','T',4)

GO
