/****************************************************************************/
/* Script to add new NAMESERVER and TAXON_GROUP tables											*/
/* and make other field changes required for NAMESERVER support 						*/
/****************************************************************************/


if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[NAMESERVER]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[NAMESERVER]
GO

CREATE TABLE [dbo].[NAMESERVER] (
	[INPUT_TAXON_VERSION_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TAXON_VERSION_FORM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TAXON_VERSION_STATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TAXON_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RECOMMENDED_TAXON_VERSION_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RECOMMENDED_TAXON_LIST_ITEM_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ENTERED_BY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[ENTRY_DATE] [datetime] NOT NULL ,
	[CHANGED_BY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CHANGED_DATE] [datetime] NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NAMESERVER] ADD 
	CONSTRAINT [PK_NAMESERVER] PRIMARY KEY  CLUSTERED 
	(
		[INPUT_TAXON_VERSION_KEY]
	)  ON [PRIMARY] ,
	CONSTRAINT [CK_NAMESERVER] CHECK ([TAXON_TYPE] = 'V' or [TAXON_TYPE] = 'S'),
	CONSTRAINT [CK_NAMESERVER_FORM] CHECK ([TAXON_VERSION_FORM] = 'U' or ([TAXON_VERSION_FORM] = 'I' or [TAXON_VERSION_FORM] = 'W')),
	CONSTRAINT [CK_NAMESERVER_STATUS] CHECK ([TAXON_VERSION_STATUS] = 'U' or ([TAXON_VERSION_STATUS] = 'S' or [TAXON_VERSION_STATUS] = 'R'))
GO

ALTER TABLE [dbo].[NAMESERVER] ADD 
	CONSTRAINT [FK_NAMESERVER_TAXON_LIST_ITEM_RECOMMENDED] FOREIGN KEY 
	(
		[RECOMMENDED_TAXON_LIST_ITEM_KEY]
	) REFERENCES [dbo].[TAXON_LIST_ITEM] (
		[TAXON_LIST_ITEM_KEY]
	),
	CONSTRAINT [FK_NAMESERVER_TAXON_VERSION] FOREIGN KEY 
	(
		[INPUT_TAXON_VERSION_KEY]
	) REFERENCES [dbo].[TAXON_VERSION] (
		[TAXON_VERSION_KEY]
	),
	CONSTRAINT [FK_NAMESERVER_TAXON_VERSION_RECOMMENDED] FOREIGN KEY 
	(
		[RECOMMENDED_TAXON_VERSION_KEY]
	) REFERENCES [dbo].[TAXON_VERSION] (
		[TAXON_VERSION_KEY]
	)
GO

IF EXISTS(SELECT 1 from SysConstraints WHERE Object_Name(constid)='FK_TAXON_GROUP_TAXON_LIST' AND ID = Object_ID('Taxon_Group'))
	ALTER TABLE Taxon_Group
		DROP CONSTRAINT FK_TAXON_GROUP_TAXON_LIST

IF EXISTS(SELECT 1 from SysConstraints WHERE Object_Name(constid)='FK_TAXON_VERSION_TAXON_GROUP' AND ID = Object_ID('Taxon_Version'))
	ALTER TABLE Taxon_Version
		DROP CONSTRAINT FK_TAXON_VERSION_TAXON_GROUP



if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[TAXON_GROUP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[TAXON_GROUP]
GO

CREATE TABLE [dbo].[TAXON_GROUP] (
	[TAXON_GROUP_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[TAXON_GROUP_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[SORT_ORDER] [int] NULL ,
	[USE_TAXON_LIST_KEY] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TAXON_GROUP] ADD 
	CONSTRAINT [PK_TAXON_GROUP] PRIMARY KEY  CLUSTERED 
	(
		[TAXON_GROUP_KEY]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TAXON_GROUP] ADD 
	CONSTRAINT [FK_TAXON_GROUP_TAXON_LIST] FOREIGN KEY 
	(
		[USE_TAXON_LIST_KEY]
	) REFERENCES [dbo].[TAXON_LIST] (
		[TAXON_LIST_KEY]
	)
GO

IF EXISTS(SELECT 1 from SysConstraints WHERE Object_Name(constid)='FK_TAXON_VERSION_TAXON_GROUP' AND ID = Object_ID('TAXON_VERSION'))
	ALTER TABLE TAXON_VERSION
		DROP CONSTRAINT FK_TAXON_VERSION_TAXON_GROUP

IF NOT EXISTS(SELECT 1 FROM SysColumns WHERE Name='Output_Group_Key' AND ID=Object_ID('Taxon_Version'))
	ALTER TABLE [dbo].[TAXON_VERSION] ADD
		OUTPUT_GROUP_KEY [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	GO

ALTER TABLE [dbo].[TAXON_VERSION] ADD 
	CONSTRAINT [FK_TAXON_VERSION_TAXON_GROUP] FOREIGN KEY 
	(
		[OUTPUT_GROUP_KEY]
	) REFERENCES [dbo].[TAXON_GROUP] (
		[TAXON_GROUP_KEY]
	)
GO

IF NOT EXISTS(SELECT 1 FROM SysColumns WHERE Name='RECOMMENDED_TAXON_LIST_ITEM_KEY' AND ID=Object_ID('INDEX_TAXON_NAME'))
	ALTER TABLE [dbo].[INDEX_TAXON_NAME] ADD
		RECOMMENDED_TAXON_LIST_ITEM_KEY [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		SORT_ORDER [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO

IF EXISTS(SELECT 1 from SysConstraints WHERE Object_Name(constid)='FK_INDEX_TAXON_NAME_TAXON_LIST_ITEM_RECOMMENDED' AND ID = Object_ID('INDEX_TAXON_NAME'))
	ALTER TABLE INDEX_TAXON_NAME
		DROP CONSTRAINT FK_INDEX_TAXON_NAME_TAXON_LIST_ITEM_RECOMMENDED

ALTER TABLE [dbo].[INDEX_TAXON_NAME] ADD
	CONSTRAINT [FK_INDEX_TAXON_NAME_TAXON_LIST_ITEM_RECOMMENDED] FOREIGN KEY 
	(
		[RECOMMENDED_TAXON_LIST_ITEM_KEY]
	) REFERENCES [dbo].[TAXON_LIST_ITEM] (
		[TAXON_LIST_ITEM_KEY]
	)
GO


GRANT SELECT ON Taxon_Group TO Public
GRANT SELECT ON Nameserver TO Public
GO