/*****Change to add Redundant Flag to Taxon Detail Meta data ******/
/****** Object:  StoredProcedure [dbo].[usp_Taxon_Select_ForMetadata]    Script Date: 09/15/2020 18:07:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*===========================================================================*\
  Description:
	Returns information about a taxon.

  Parameters:
	@Key	Key of the taxon list item.

  Created:	July 2009 
  Updated 	September 2020 - Pick up the redundant flag 

 

\*===========================================================================*/

ALTER PROCEDURE [dbo].[usp_Taxon_Select_ForMetadata]
	@Key	CHAR(16)
AS
	SET NOCOUNT ON

	SELECT	T.Taxon_Key,
			T.Item_Name,
			T.Entered_By,
			T.Entry_Date,
			T.Changed_By,
			T.Changed_Date,
			Tv.Taxon_Version_Key,
			TLI.Taxon_List_Item_Key,
			TG.Taxon_Group_Name,
			TLT.SHORT_NAME AS TAXON_LIST_TYPE,
			ITN.PREFERRED_NAME AS PREFERRED_NAME, 
			ITN.RECOMMENDED_TAXON_LIST_ITEM_KEY AS RECOMMENDED_TLI_KEY,
			ITN2.TAXON_VERSION_KEY AS RECOMMENDED_TV_KEY,
			ITN2.ACTUAL_NAME AS RECOMMENDED_NAME,
			ITN2.COMMON_NAME AS RECOMMENDED_COMMON_NAME,
			ITN2.SORT_ORDER AS RECOMMENDED_SORT_ORDER,
			TL2.ITEM_NAME AS RECOMMENDED_LIST,
			TLT2.SHORT_NAME AS RECOMMENDED_LIST_TYPE,
			O.ORGANISM_KEY AS ORGANISM_KEY,
			O.TAXON_VERSION_KEY AS ORGANISM_TVK,
			O.REDUNDANT_FLAG AS REDUNDANT_FLAG
				
			
	FROM	Taxon_List_Item		TLI
	JOIN	Taxon_Version		TV	ON TV.Taxon_Version_Key	= TLI.Taxon_Version_Key
	JOIN	Taxon				T	ON T.Taxon_Key			= TV.Taxon_Key
	INNER JOIN TAXON_GROUP TG ON TG.TAXON_GROUP_KEY = TV.OUTPUT_GROUP_KEY
	INNER JOIN INDEX_TAXON_NAME ITN ON ITN.TAXON_LIST_ITEM_KEY =
	TLI.TAXON_LIST_ITEM_KEY 
	INNER JOIN INDEX_TAXON_NAME ITN2 ON ITN2.TAXON_LIST_ITEM_KEY =
	ITN.RECOMMENDED_TAXON_LIST_ITEM_KEY
	INNER JOIN TAXON_LIST_VERSION TLV ON TLV.TAXON_LIST_VERSION_KEY =
	ITN.TAXON_LIST_VERSION_KEY 
	INNER JOIN TAXON_LIST TL ON TL.TAXON_LIST_KEY = TLV.TAXON_LIST_KEY  
	INNER JOIN TAXON_LIST_TYPE TLT ON TLT.TAXON_LIST_TYPE_KEY =
	TL.TAXON_LIST_TYPE_KEY
	
	INNER JOIN TAXON_LIST_VERSION TLV2 ON TLV2.TAXON_LIST_VERSION_KEY =
	ITN2.TAXON_LIST_VERSION_KEY 
	INNER JOIN TAXON_LIST TL2 ON TL2.TAXON_LIST_KEY = TLV2.TAXON_LIST_KEY  
	INNER JOIN TAXON_LIST_TYPE TLT2 ON TLT2.TAXON_LIST_TYPE_KEY =
	TL2.TAXON_LIST_TYPE_KEY
	
	LEFT JOIN ORGANISM O ON O.TAXON_VERSION_KEY =
	ITN2.TAXON_VERSION_KEY 
	
		
	WHERE	TLI.Taxon_List_Item_Key = @Key
