-- Update spatial ref column sizes to 40
ALTER TABLE Sample
ALTER COLUMN SPATIAL_REF VARCHAR(40) NULL
GO

ALTER TABLE Survey_Event
ALTER COLUMN SPATIAL_REF VARCHAR(40) NULL
GO

ALTER TABLE Survey
ALTER COLUMN SW_SPATIAL_REF VARCHAR(40) NULL
GO

ALTER TABLE Survey
ALTER COLUMN NE_SPATIAL_REF VARCHAR(40) NULL
GO

ALTER TABLE Location
ALTER COLUMN SPATIAL_REF VARCHAR(40) NULL
GO

-- Update report attribbutes
UPDATE Report_Field
SET Field_Size=40
WHERE Report_Field_Key IN ('NBNSYS0000000004', 'NBNSYS0000000005', 'NBNSYS0000000025', 'NBNSYS0000000027')

