UPDATE Report_Join 
SET Join_SQL='FROM
#REPORT_OUTPUT
LEFT JOIN
BIOTOPE_DETERMINATION
LEFT JOIN
BIOTOPE_LIST_ITEM
LEFT JOIN
BIOTOPE_CLASSIFICATION_VERSION
LEFT JOIN
BIOTOPE_CLASSIFICATION
ON BIOTOPE_CLASSIFICATION_VERSION.BIOTOPE_CLASSIFICATION_KEY = BIOTOPE_CLASSIFICATION.BIOTOPE_CLASSIFICATION_KEY
ON BIOTOPE_LIST_ITEM.BT_CL_VERSION_KEY = BIOTOPE_CLASSIFICATION_VERSION.BT_CL_VERSION_KEY
ON BIOTOPE_DETERMINATION.BIOTOPE_LIST_ITEM_KEY = BIOTOPE_LIST_ITEM.BIOTOPE_LIST_ITEM_KEY
	AND BIOTOPE_DETERMINATION.Preferred=1 
ON #REPORT_OUTPUT.OCCURRENCE_KEY = BIOTOPE_DETERMINATION.BIOTOPE_OCCURRENCE_KEY'
WHERE Report_Join_Key='NBNSYS0000000037'

UPDATE Report_Join 
SET Join_SQL='FROM
#REPORT_OUTPUT
LEFT JOIN
BIOTOPE_DETERMINATION
LEFT JOIN
BIOTOPE_LIST_ITEM
LEFT JOIN
BIOTOPE
ON BIOTOPE_LIST_ITEM.BIOTOPE_KEY = BIOTOPE.BIOTOPE_KEY
ON BIOTOPE_DETERMINATION.BIOTOPE_LIST_ITEM_KEY = BIOTOPE_LIST_ITEM.BIOTOPE_LIST_ITEM_KEY
	AND BIOTOPE_DETERMINATION.Preferred=1 
ON #REPORT_OUTPUT.OCCURRENCE_KEY = BIOTOPE_DETERMINATION.BIOTOPE_OCCURRENCE_KEY'
WHERE Report_Join_Key='NBNSYS0000000038'